<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.lippia</groupId>
        <artifactId>root</artifactId>
        <version>3.3.0.3</version>
    </parent>

    <groupId>com.Crowdar</groupId>
    <artifactId>lippia-low-code-sample-project</artifactId>
    <name>low-code-automation</name>
    <packaging>jar</packaging>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <base.api.url>https://api.clockify.me/api</base.api.url>
        <cucumber.stepsDefinitions>--glue io/lippia/api/lowcode/steps --glue ar/steps</cucumber.stepsDefinitions>
        <cucumber.hooks>--glue com/crowdar/bdd/cukes --glue ar/apiExampleProject/hook</cucumber.hooks>
		<cucumber.tags>@smoke</cucumber.tags>
        <crowdar.cucumber.plugins>--plugin pretty --plugin com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter: --plugin com.crowdar.examples.listeners.CucumberListener:</crowdar.cucumber.plugins>
        <crowdar.reporter.avent>true</crowdar.reporter.avent>
        <crowdar.extent.host.name>LocalMachine</crowdar.extent.host.name>
        <crowdar.extent.environment>Local</crowdar.extent.environment>
        <crowdar.extent.user.name>User.name</crowdar.extent.user.name>
        <cucumber.reporters>--plugin pretty --plugin ar.reports.CucumberReporter: </cucumber.reporters>
        <test-manager.report>--plugin ar.reports.TestManagerReporter:</test-manager.report>
		<crowdar.cucumber.option>src/test/resources/features ${cucumber.hooks} ${cucumber.stepsDefinitions} --tags 'not @Ignore' --tags ${cucumber.tags} ${cucumber.reporters}</crowdar.cucumber.option>
        <crowdar.projectType>API</crowdar.projectType>
        <environment></environment>
    </properties>

    <profiles>
        <profile>
            <id>Secuencial</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <apiExample.runner>testngSecuencial.xml</apiExample.runner>
            </properties>
        </profile>
        <profile>
            <id>Paralelo</id>
            <properties>
                <apiExample.runner>testngParalell.xml</apiExample.runner>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
	        <groupId>io.lippia</groupId>
	        <artifactId>core</artifactId>
	        <version>3.3.0.3</version>
        </dependency>
        <dependency>
            <groupId>io.lippia.report</groupId>
            <artifactId>ltm-cucumber4-adapter</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>io.lippia.report</groupId>
            <artifactId>extentreports-cucumber4-adapter</artifactId>
            <version>1.1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>5.1.1</version>
        </dependency>

        <!-- configurations management -->
        <dependency>
            <groupId>com.typesafe</groupId>
            <artifactId>config</artifactId>
            <version>1.4.2</version>
        </dependency>
        <dependency>
             <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10</version>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.28.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>5.2.10.RELEASE</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc10</artifactId>
            <version>19.17.0.0</version>
        </dependency>

    </dependencies>
    <build>
        <filters>
            <filter>src/main/resources/cucumber.properties</filter>
        </filters>
        <plugins>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M4</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>${apiExample.runner}</suiteXmlFile>
                    </suiteXmlFiles>
                    <systemPropertyVariables>
                        <TEST_MANAGER_USERNAME></TEST_MANAGER_USERNAME>
                        <TEST_MANAGER_PASSWORD></TEST_MANAGER_PASSWORD>
                        <TEST_MANAGER_API_HOST></TEST_MANAGER_API_HOST>
                        <TEST_MANAGER_API_PORT></TEST_MANAGER_API_PORT>
                        <TEST_MANAGER_RUN_NAME></TEST_MANAGER_RUN_NAME>
                        <TEST_MANAGER_PROJECT_CODE></TEST_MANAGER_PROJECT_CODE>
                        <TEST_MANAGER_REPOSITORY_URL></TEST_MANAGER_REPOSITORY_URL>
                        <TEST_MANAGER_REPOSITORY_BRANCH></TEST_MANAGER_REPOSITORY_BRANCH>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <repositories>
		<repository>
			<id>central</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>

</project>
